### ISSUE TITLE
stop using MethodViews in flask apps

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#1102]
Plain functions are just fine.

(Imported from https://bugzilla.mozilla.org/show_bug.cgi?id=1508137, filed by @allan-silva)

**Comment by michellemounde** [comment]
@bhearsum I have some clarifying questions for this issue.

1. Does this mean that in a function such as:

https://github.com/mozilla-releng/balrog/blob/ab3882c1c040770dfb779155092fe3d468571ea5/src/auslib/web/admin/emergency_shutoff.py#L48C1-L50

Instead we would have the get function that is in the ScheduledChangeView:

https://github.com/mozilla-releng/balrog/blob/ab3882c1c040770dfb779155092fe3d468571ea5/src/auslib/web/admin/views/scheduled_changes.py#L61-L73

2. How would we deal with the base views that the views inherit from i.e. AdminView and HistoryView

**Comment by bhearsum** [comment]
To answer the second question first -- any code that is shared by multiple views would need to be refactored to be a plain function (not a class method), which the new view functions could then call. This is actually what is already happening in `emergency_shutoffs.py`. It is _not_ happening in files like https://github.com/mozilla-releng/balrog/blob/ab3882c1c040770dfb779155092fe3d468571ea5/src/auslib/web/admin/views/rules.py#L54, where we have a number of classes with methods on them that implement various endpoints.

(This code is connected to an endpoint name through https://github.com/mozilla-releng/balrog/blob/ab3882c1c040770dfb779155092fe3d468571ea5/src/auslib/web/admin/swagger/api.yml#L1990 via https://github.com/mozilla-releng/balrog/blob/ab3882c1c040770dfb779155092fe3d468571ea5/src/auslib/web/admin/views/mapper.py.)

**Comment by michellemounde** [comment]
@bhearsum Thank you for the detailed explanation on my second question. After going through the linked files again, I now understand how plain functions would work as the base in place of the base views.
