### ISSUE TITLE
don't prompt for signoff with roles that aren't relevant

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#1145]
Examples:
- If `releng` and `relman` are required for a change, and a user holds `releng` and `tb-releng`, we currently show a prompt that allow the user to sign off with either. We should just automatically sign off with `releng` instead.
- If `releng` and `relman` are required for a change, and a user holds `releng`, `relman`, and `tb-releng`, we currently show a prompt that allow the user to sign off with any of them. We should still show a prompt in this case, but only allow `releng` or `relman` to be used.

**Comment by escapewindow** [comment]
<img width="845" alt="Screen Shot 2021-04-02 at 9 41 58 AM" src="https://user-images.githubusercontent.com/826343/113435514-d0f51700-9397-11eb-88d6-4349345f52fa.png">

**Comment by ruthEnanga** [comment]
@bhearsum 
I will like to work on this
Can it be assigned to me?

**Comment by CREDO23** [comment]
What happens if the user holds `tb-releng` and the required are `relman` and/or `releng` ?

**Comment by bhearsum** [comment]
> @bhearsum I will like to work on this Can it be assigned to me?

Hi, please feel free to work on the issue and open a PR when you feel it is ready.

**Comment by CREDO23** [comment]
Okay, let me add this feature!

**Comment by bhearsum** [comment]
Fixed by #3021
