### ISSUE TITLE
consider showing what signoffs are required when updating rules

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/balrog#1147]
when selecting `update` on a rule, it wasn't obvious if the rule required signoffs or who needed to sign off until the actual update was made.

e.g. here:

<img width="899" alt="Screen Shot 2019-09-20 at 11 24 17 AM" src="https://user-images.githubusercontent.com/1648433/65349900-60155200-db99-11e9-84ba-92ad26460e25.png">

it be neat if to show the signoffs required below or above the timestamp requirements in the update page:

<img width="1012" alt="Screen Shot 2019-09-20 at 11 26 09 AM" src="https://user-images.githubusercontent.com/1648433/65349972-84712e80-db99-11e9-9b5e-aadf429b89f1.png">

**Comment by Barry-dE** [comment]
I'd love to work on this. Please assign it to me.

**Comment by Raven49** [comment]
Kindly assign this task to me
