### ISSUE TITLE
updating a rule ignore the "when" field

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/balrog#1223]
I've been trying to schedule rule changes but even though I change the "when" field to be an hour in the future, the UI tells me "This will be scheduled for ASAP", and indeed saving the change schedules it for a few seconds later.

**Comment by jcristau** [comment]
Nevermind, this was an AM/PM thing...

**Comment by mozbhearsum** [comment]
Hm, the UI sets it to 30s in the future if you try to select something in the past. This was designed to handle the case where the prefilled time (30s in the future) ended up in the past when you tried to save the changes. I wonder if we should avoid doing this if the time has been set manually....
