### ISSUE TITLE
please provide an optional "comment" field for emergency_shutoff

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/balrog#1862]
Something that came up recently is it might be useful if we could document the reason for emergency shutoffs, more or less in the same way that we do for rules (or for tree closures in treestatus), typically by pointing to a bug number.  Then https://aus-api.mozilla.org/api/v1/emergency_shutoff/Firefox/nightly could be used by interested parties to know what's going on when they're not getting updates.

cc @Archaeopteryx

**Comment by gabrielBusta** [comment]
I like this idea. Would this still be useful? Seems like a good quality of live improvement

**Comment by Archaeopteryx** [comment]
Yes, that's still desired. @pascalchevrel added the state if updates are enabled to https://fx-trains.herokuapp.com/release/?version=nightly and the reason would also fit right there.

**Comment by allan-silva** [comment]
Hi, can I take this issue ?

**Comment by jcristau** [comment]
@allan-silva that'd be great :)
