### ISSUE TITLE
use content signatures for GMP update responses

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#2106]
We want to get rid of cert pinning for GMP updates, but before doing so we need to provide Content Signatures for the responses as an alternate way for the client to authenticate them. We already do this signing for Mozilla VPN, so all the Balrog primitives and autograph links are in place. We just need code similar to https://github.com/mozilla-releng/balrog/blob/main/src/auslib/web/public/json.py#L24 to make and attach the signatures.

There's only a small handful of unique GMP responses, so I don't expect load on autograph will be a big issue here, as we can do some caching similar to the above code.

It's important that we limit this _just_ to GMP, because if we started signing Firefox or System Addons responses, that would generate significant load on autograph.

https://bugzilla.mozilla.org/show_bug.cgi?id=1714621 has more background and context on this.

**Comment by SingingTree** [comment]
With this closed, should client code be ready to try and use the signatures? Or is there more I should wait on before I start dabbling?

**Comment by gbrownmozilla** [comment]
This is in production now and should be ready to use.
