### ISSUE TITLE
UI shows scheduled deletions for unrelated channels

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/balrog#2312]
Looking at e.g. https://balrog.services.mozilla.com/rules?product=SystemAddons&channel=beta, I shouldn't see scheduled deletions for SystemAddons/esr rules.

**Comment by conceptacherono** [comment]
can this be assigned to me

**Comment by CREDO23** [comment]
Could I have more information about this issue @bhearsum, @gabrielBusta ?

**Comment by Raven49** [comment]
can this task be assigned to me please

**Comment by bhearsum** [comment]
Hi, please feel free to work on the issue and open a PR when you feel it is ready. Even if we get multiple PRs for the same issue it will be good experience for you!

**Comment by godplayer56** [comment]
![Screenshot from 2023-10-29 00-16-13](https://github.com/mozilla-releng/balrog/assets/121134233/3fb15049-b045-4f92-b380-2b07bbf148d3)
This error is being shown to me, is there anything that I am doing wrong while accessing the link? I have installed the ssh certificates for my browser.

**Comment by bhearsum** [comment]
This is expected, you do not have access to the production server :). You can replicate the error on https://localhost:9000 by scheduling a deletion of a SystemAddons:esr rule, and seeing that it is present on https://localhost:9000/rules?product=SystemAddons&channel=beta

**Comment by godplayer56** [comment]
Ok will try this :)
