### ISSUE TITLE
Frequent failures (NetworkError) viewing Releases in staging admin ui

### ISSUE THREAD

**Issue by gbrownmozilla** [mozilla-releng/balrog#2401]
https://balrog-admin-static-stage.stage.mozaws.net/releases frequently (always?) fails with "Error contacting Balrog backend: Error: Network Error. Are you connected to the VPN?"

I do not see the same problem in production.

**Comment by gbrownmozilla** [comment]
Any relation to #1737 ?

**Comment by gbrownmozilla** [comment]
There are errors in sentry for staging-admin: AttributeError: 'Request' object has no attribute 'transaction'

**Comment by gbrownmozilla** [comment]
That is happening in complete_request(), and request.transaction should have been set in setup_request(), so it's not obvious what could be going wrong.

**Comment by jcristau** [comment]
Do you see anything in the devtools network tab when this happens?  For some reason it loads just fine here.

**Comment by gbrownmozilla** [comment]
I guess it fixed itself? I can no longer reproduce.

**Comment by gbrownmozilla** [comment]
ahal initially experienced this problem. jcristau noted that ahal needed to be added as a balrog user on stage and fixed that. Was that related to the NetworkError, or confused with it, or...? 

Anyway, seemed to be a temporary condition.
