### ISSUE TITLE
busted dependencies for tests

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/balrog#2530]
Not sure if this is true for prod or just tests, but

- for 940d5865531b75e4d5cca49cde794b9f533234c9 , tests are busted on an unpinned pyjwt even though it's pinned in base.txt, and
- when @gabrielBusta and I tried to re-pin deps (with `--allow-unsafe`, we die on `repoze-lru`.

If there's a workaround, we can use it, but we may want to do something more invasive, e.g. find an alternative for `repoze-lru`.

**Comment by gabrielBusta** [comment]
I haven't been able to find a work around. repoze-lru hasn't been published since 2017. looking for an alternative (maybe the native lru cache in functools?)

**Comment by escapewindow** [comment]
Yeah, I think functools `lru_cache` will probably work.

**Comment by jcristau** [comment]
IIRC I hit issues with `repose-lru` vs `repoze.lru` in the requirements file a while back that I never quite understood, where one worked and the other didn't.  That may not help here and may not even matter if we can switch to cachetools or something.

**Comment by gabrielBusta** [comment]
Ah I see. It's worth a try. Thanks
