### ISSUE TITLE
Error on docker-compose up - apt-get: not found

### ISSUE THREAD

**Issue by allan-silva** [mozilla-releng/balrog#2601]
`docker-compose up` command results in "apt-get: not found" error.

This happens because  `mysql:5.7` is based on [oraclelinux:7-slim](https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile.oracle) , we can use `mysql:5.7-debian`instead.

In addition, we have a duplication of the `links` attribute on balrogpub service in docker-compose: https://github.com/mozilla-releng/balrog/blob/5dd66b17357d8cb1c3912f5e2437fdb5af866a3c/docker-compose.yml#L65-L92

**Comment by jcristau** [comment]
Interesting. I wonder when they changed this...

**Comment by jcristau** [comment]
For the record: https://github.com/docker-library/mysql/pull/867 is where this changed, a few weeks ago.
