### ISSUE TITLE
Emergency shutoff button is clickable when it is disabled

### ISSUE THREAD

**Issue by allan-silva** [mozilla-releng/balrog#2610]
Found while working on #2604 (maybe a good first bug)

When product/channel is not  selected:
![image](https://user-images.githubusercontent.com/9947646/182141905-ffc9233a-d4b2-4e80-8989-ad245a7fd86f.png)

When updates is already disabled:
![image](https://user-images.githubusercontent.com/9947646/182142105-6a630b77-29d7-4f5a-9bae-1e661b6b3287.png)

**Comment by mays4** [comment]
I am an outreach applicant, I don't see the first-bug issue available (all assigned or commented by applicants), so can I work on this issue?

**Comment by allan-silva** [comment]
Hey @gabrielBusta, can you assign this issue to @mays4 ?
It looks like a `good-first-bug`.

**Comment by MelakuAlehegn** [comment]
@gabrielBusta @bhearsum there has been no PR on this issue, can I work on it?

**Comment by MelakuAlehegn** [comment]
@allan-silva can you provide more context on which pages to look for, files to edit?

**Comment by bhearsum** [comment]
The fix will almost certainly be in https://github.com/mozilla-releng/balrog/blob/main/ui/src/views/Rules/ListRules/index.jsx#L137. Based on @allan-silva's earlier comment & screenshot it sounds like `productChannelQueries` may not be set when an emergency shutoff has been done. My suggestion would be to add some `console.log` messages to this file and then:
* Visit https://localhost:9000/rules?product=Firefox&channel=release
* Open the Developer Tools Console
* Reload the page, and make note of any log messages that show up
* Use "Disable updates" in the bottom right of the view to set the emergency shutoff
* Reload the page, and compare the log messages that show up this time

**Comment by MelakuAlehegn** [comment]
@bhearsum Thanks for your prompt response. Taking a look..

**Comment by AMUZY** [comment]
I tried to replicate the issue @bhearsum but there seems to be no issue with this. I followed the steps as well as @allan-silva's message and the page seems to be fine. 
I had no errors in my debug tools when I disabled updates for a product (`Firefox : Release`) in my case,  and then selected `All Rules`.
Maybe this has been fixed? Or I'm not replicating the issue correctly?
@MelakuAlehegn have you been able to replicate this issue?

**Comment by AMUZY** [comment]
Can't see any error that looks like the image @allan-silva shared

**Comment by allan-silva** [comment]
Hello everyone, try to reproduce in the following order:
1) Click on rules;
2) On rules page, select a product/channel (eg.: Firefox : Nightly);
3) Click on "pause button" to disable product/channel updates;
4) Optionally say the reason and click "Yes".

Now updates for product/channel are disabled.

![image](https://github.com/mozilla-releng/balrog/assets/9947646/f3d56bf5-e430-4c7d-8235-4d395196f06c)

5) repeate the steps 3 and 4 (notice the pause button is disabled, but is clickable)

![image](https://github.com/mozilla-releng/balrog/assets/9947646/c5ad1850-2136-42b7-b50e-5dd8c74181f5)
![image](https://github.com/mozilla-releng/balrog/assets/9947646/858dde84-9157-4ea3-be79-cb7ef71d6bc2)

**Comment by AMUZY** [comment]
Ooooh ! Let me do this

**Comment by MelakuAlehegn** [comment]
@allan-silva it looks like the button is clickable for disabled updates, as you explained. Confirming that the  error exists.
![image](https://github.com/mozilla-releng/balrog/assets/49185991/7822eb89-fa04-4ba5-af1f-acae6d91e0e1)

**Comment by AMUZY** [comment]
Hi @bhearsum @gabrielBusta this ISSUE has been solved [HERE](https://github.com/mozilla-releng/balrog/pull/3028) and is safe to be close now I guess. Bless y'all

**Comment by bhearsum** [comment]
Thanks, we missed that!
