### ISSUE TITLE
Upgrade to MySQL 8.0

### ISSUE THREAD

**Issue by jbuck** [mozilla-releng/balrog#2714]
MySQL 5.7 is [EOL October 2023](https://endoflife.date/mysql) so we should start thinking about when to do this upgrade for Balrog.

**Comment by jbuck** [comment]
We've upgraded dev & stage to mysql 8.0.26 (the default CloudSQL version)

**Comment by jcristau** [comment]
Based on testing with a replica, the production database upgrade should take around 17 minutes, during which the db will be intermittently available, which will affect both the admin and public facing apps.
Our take is that this is a short enough down time and we can do the upgrade in-place in production without taking extra steps to minimize impact on the public app (aus5.mozilla.org).
If we're agreed then we can either do it during evening ET hours as that seems to have least traffic, or during our business hours to more easily respond to any issues.
@rvandermeulen any opinions/thoughts on the above?

**Comment by rvandermeulen** [comment]
During the day when people are around seems like the safer option. This week would be good in general given that's a pretty quiet one in the release cycle.

**Comment by jbuck** [comment]
Production has been upgraded to use MySQL 8.0.26
