### ISSUE TITLE
CI: release decision task fails

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/balrog#2738]
#2719 made the push-image task in the github-release graph depend on test tasks, including test-backend, which needs the coveralls secret.  However we only grant that secret to pull-requests and pushes to main (and we don't currently index / optimize out the dependency using the on-push graph).

@gbrownmozilla @gabrielBusta do you have thoughts on adding the scope vs just not re-running the tests before push-image?

**Comment by gbrownmozilla** [comment]
I don't have strong feelings, but lean toward not re-running the tests.
