### ISSUE TITLE
Better metrics for in-memory caches

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#2766]
Balrog has a number of in-memory caches for, primarily, results from the database and autograph. At the moment, we have zero insight into how well these perform: the hit rates, the refresh rates, whether or not we dump things out to make room for new things. It would be wonderful to have this information produced in a way that we can graph in graphana (or somewhere else).

@jcristau - does this cover what you were thinking of?

**Comment by jbuck** [comment]
as a first pass at this, could you output some statsd metrics on cache requests, hits, and misses?

**Comment by jcristau** [comment]
@bhearsum should we consider this done, given https://earthangel-b40313e5.influxcloud.net/d/oe5DkggNz/balrog-caches?orgId=1?

**Comment by bhearsum** [comment]
Yup, sounds good to me.
