### ISSUE TITLE
rule edit pages take too long to load when there's a lot of v2 releases

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#2785]
Currently, loads of /api/v2/releases are timing out in balrog production after 60 seconds, causing rule edit pages to fail to work. These queries are ultimately fulfilled by [this code](https://github.com/mozilla-releng/balrog/blob/f5fd742d39a40491d11c694b910ae24012161ac8/src/auslib/services/releases.py#L258), which joins to a whole bunch of tables - so it's no wonder it's so slow.

We really only need the names of the releases to fulfill the needs here - so we ought to use a different endpoint. I see two options (although maybe there's more):
1) Add a new v2 endpoint that's powered by [get_release_names](https://github.com/mozilla-releng/balrog/blob/f5fd742d39a40491d11c694b910ae24012161ac8/src/auslib/services/releases.py#L250)
2) Add an endpoint to the admin app that's powered by [release_list](https://github.com/mozilla-releng/balrog/blob/f5fd742d39a40491d11c694b910ae24012161ac8/src/auslib/web/common/releases.py#L24) -- which queries both v1 and v2 releases, and can return names only. (We already have an endpoint like this for the public API.)

In either case, we need to [update the UI code to cope with the change](https://github.com/mozilla-releng/balrog/blob/f5fd742d39a40491d11c694b910ae24012161ac8/ui/src/views/Rules/Rule/index.jsx#L169-L178).

**Comment by jcristau** [comment]
Fixed by #2787
