### ISSUE TITLE
OS version is cropped when approximately more than 2 versions are provided

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/balrog#2943]
A few weeks ago, we created this Balrog rule that prevents Firefox users on deprecated Windows and macOS versions to be updated. The rule list 6 OS versions, but only 2 are visible: 

![image](https://github.com/mozilla-releng/balrog/assets/5907366/ba31dfea-c13d-4c14-aef6-18c35babb7bb)

The list should have displayed:

```
Windows_NT 6.1,Windows_NT 6.2,Windows_NT 6.3,Darwin 16,Darwin 17,Darwin 18
```

Let's change the UI to show all OS versions at once.

**Comment by akankshat05** [comment]
hello, I can fix this issue, please assign this to me. thank you.

**Comment by AbassKoyang** [comment]
> hello, I can fix this issue, please assign this to me. thank you.

Are you still working on it? can i take it up?

**Comment by akankshat05** [comment]
> > hello, I can fix this issue, please assign this to me. thank you.
> 
> Are you still working on it? can i take it up?

Yes, I am working on it.

**Comment by godplayer56** [comment]
![Screenshot from 2023-10-06 16-06-09](https://github.com/mozilla-releng/balrog/assets/121134233/d945fd59-314d-4e67-a157-a11ac8a1a32f)
Is this an issue with this function?
I think we can use text wrapping for this.

**Comment by sumairq** [comment]
It is solved by removing 

```
 secondaryTypographyProps={{
                        className: classes.textEllipsis,
                      }}
``` 
from `ListItemText` 

https://github.com/mozilla-releng/balrog/blob/860e3bb34c7c0de73a9dc3d4419787bbf0810b13/ui/src/components/RuleCard/index.jsx#L560C17-L584C30

**Comment by CREDO23** [comment]
It is improved by making the `osVersion` a gridItem and set it to take the full width of its parent:
`<ListItem/>` → `<Grid item xs={12}>...</Grid>`

```javascript
                   <Grid xs={12}>
                          {rule.osVersion && (
                              <ListItem className={classes.listItem}>
                                 <ListItemText
                                     title={rule.osVersion.split(',').join('\n')}
                                     primaryTypographyProps={{
                                     component: 'div',
                                     className: classes.primaryText,
                                     }}
                                     primary={
                                                   <Fragment>
                                                      OS Version
                                                      {diffedProperties.includes('osVersion') &&
                                                      rule.scheduledChange.change_type === 'update' && (
                                                       <span
                                                           className={classes.propertyWithScheduledChange}
                                                       />
                                                       )}
                                                   </Fragment>
                                                    }
                                   secondary={rule.osVersion}
                                   />
                                </ListItem>
                            )}
                   </Grid>
```

Here is the [PR](https://github.com/mozilla-releng/balrog/pull/2999)
