### ISSUE TITLE
Highlight matching search terms in the search results in the Relases page

### ISSUE THREAD

**Issue by gabrielBusta** [mozilla-releng/balrog#3007]
Now that we've added partial matching for search terms in the releases page on #1146 it would be great if the matching parts of the search query are highlighted in the results. This would give visual feedback about what part of the search query matched the release.

**Comment by FatumaA** [comment]
I'll be attempting this

**Comment by nazarenegena** [comment]
@FatumaA  @gabrielBusta 
i'm already working on this as a follow up on #1146 issue
