### ISSUE TITLE
Add a unit test for the highlightMatchedRelease function

### ISSUE THREAD

**Issue by gabrielBusta** [mozilla-releng/balrog#3036]
Add a unit test for the `highlightMatchedRelease` function introduced in #3033.

**Comment by MelakuAlehegn** [comment]
Writing to notify that I'm working on this. @gabrielBusta

**Comment by michellemounde** [comment]
Hey @MelakuAlehegn yes you can work on it. All issues are available as long as they are open.
I added comments on the function in the linked PR. You can check them out to help you understand how the function works.

**Comment by gabrielBusta** [comment]
@MelakuAlehegn also, it's worth noting, there are a lot of untested logic (`.js`) modules in here:

https://github.com/mozilla-releng/balrog/tree/main/ui/src/utils

Let me know if you'd like to add tests to any of them (currently we only have tests for `rules.js`)

I would gladly open new issues!

**Comment by MelakuAlehegn** [comment]
> @MelakuAlehegn also, it's worth noting, there are a lot of untested logic (`.js`) modules in here:
> 
> https://github.com/mozilla-releng/balrog/tree/main/ui/src/utils
> 
> Let me know if you'd like to add tests to any of them (currently we only have tests for `rules.js`)

I'll be happy to add my codes there as well. @gabrielBusta
