### ISSUE TITLE
Migrate off of Neutrino

### ISSUE THREAD

**Issue by gabrielBusta** [mozilla-releng/balrog#3039]
[Neutrino](https://github.com/neutrinojs/neutrino) blocks us from upgrading certain dependencies, as well as from upgrading webpack, loaders, etc., with which Neutrino is incompatible. As long as we depend on this stale project, we miss security, performance enhancements, and new feature updates to these dependencies.

Neutrino's last release was in December of 2020, suggesting it's hardly managed now.

We should either find a new, current solution or handle the tasks Neutrino did for us on our own.

**Comment by godplayer56** [comment]
Hey @gabrielBusta I am interested in working with this issue, how should I approach solving this issue? I am confused on what all changes I need to make :sweat_smile:

**Comment by AMUZY** [comment]
Saying this here for anyone who's willing to work on this issue (if you understand Neutrino that well), it's maybe better to handle the configuration tasks Neutrino did on our own (except if there's any more recent and up-to-date tool that functions like Neutrino). 
balrog really needs to update a lot of it's dependencies, eslint,webpack,MUI,React,React DOM e.t.c. and Neutrino holds balrog back.
I'm eager to see balrog rocking v5 of MUI components😎😎😎

**Comment by gabrielBusta** [comment]
I managed to get a [neutrino free ui/webpack.config.js that compiles successfully](https://github.com/gabrielBusta/misc-public/blob/main/webpack.config.js).

**Comment by AMUZY** [comment]
Niiiceeeee !!!

**Comment by gabrielBusta** [comment]
I spoke to soon. This still had a lot of issues.
I fixed them and left some information about the issues in [this comment](https://github.com/mozilla-releng/balrog/pull/3099#issuecomment-1986343979) on #3099 
The configuration on that PR is actually in a working state. The next step is to tackle the other `.js` configuration files relying on neutrino.

**Comment by gabrielBusta** [comment]
This effort came up today at the Taskcluster community meeting. We want to migrate Taskcluster off of neutrino as well. I am [cross-linking the issue here](https://github.com/taskcluster/taskcluster/issues/5265). So we can reference this work when we tackle the issue in Taskcluster.
